env:
  node: true
  es2021: true
extends: 
  - eslint:recommended
  # - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
root: true
ignorePatterns: 
  - node_modules
  - examples
  - assets
  - vendor
  - lib
  - dist
  - temp
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars:
    - error
    - args: after-used
      caughtErrors: none
  no-var: 
    - error
  prefer-const: 
    - error
